-- AlterEnum
ALTER TYPE "OrderStatus" ADD VALUE 'CONFIRMED' AFTER 'ASSIGNED';
ALTER TYPE "OrderStatus" ADD VALUE 'HEADING_OUT' AFTER 'CONFIRMED';
ALTER TYPE "OrderStatus" ADD VALUE 'PICKING_UP' AFTER 'HEADING_OUT';
ALTER TYPE "OrderStatus" ADD VALUE 'ON_THE_WAY' AFTER 'PICKING_UP';

-- AlterTable
ALTER TABLE "orders" ADD COLUMN     "acceptedAt" TIMESTAMP(3);

-- AlterTable
ALTER TABLE "deliverers" ADD COLUMN     "queuedAt" TIMESTAMP(3);
